version: 2.1
executors:
  default:
    docker:
      - image: circleci/ruby:2.7.5

jobs:
  build:
    macos:
      xcode: "14.3.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            yarn install
      - run:
          name: Build with Fastlane
          command: fastlane build
