version: 2.1
jobs:
  build:
    macos:
      xcode: "14.3.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm install
      - run:
          name: Build with Fastlane
          command: fastlane beta
