version: 2.1

orbs:
  android: circleci/android@1.1.2
  fastlane: fastlane/fastlane@2.5.2

jobs:
  build_android:
    executor: android/default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            nvm install 16.16
            npm install -g react-native-cli
            npm install
      - run:
          name: Build Android APK
          command: |
            cd android && ./gradlew assembleRelease
      - store_artifacts:
          path: android/app/build/outputs/apk/release/app-release.apk
          destination: app-release.apk

  build_ios:
    macos:
      xcode: "14.1.0"
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            nvm install 16.16
            npm install -g react-native-cli
            npm install
      - run:
          name: Build iOS IPA
          command: |
            bundle install
            bundle exec fastlane ios build_app
      - store_artifacts:
          path: ios/build/*.ipa
          destination: app.ipa

workflows:
  build:
    jobs:
      - build_android
      - build_ios:
          requires:
            - build_android