version: 2.1

jobs:
  build:
    macos:
      xcode: "14.1"
    environment:
      RUBY_VERSION: "2.7.5"
      NODE_VERSION: "16.16"
    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install Node.js
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
            source ~/.nvm/nvm.sh
            nvm install $NODE_VERSION

      - run:
          name: Install Java and Android SDK
          command: |
            sudo apt-get update && sudo apt-get install -y openjdk-8-jdk
            export ANDROID_HOME=~/android-sdk-linux
            curl https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip --output commandlinetools-linux.zip
            mkdir -p $ANDROID_HOME/cmdline-tools
            unzip -d $ANDROID_HOME/cmdline-tools commandlinetools-linux.zip
            export PATH=$PATH:$ANDROID_HOME/cmdline-tools/tools/bin
            yes | sdkmanager --licenses
            sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - run:
          name: Install dependencies and build app
          command: |
            bundle config set path vendor/bundle
            bundle install
            yarn install
            yarn android:build
            yarn ios:build

      # Artifacts
      - store_artifacts:
          path: android/app/build/outputs
          destination: android
          when: on_success

      - store_artifacts:
          path: ios/build
          destination: ios
          when: on_success

workflows:
  build_and_test:
    jobs:
      - build