version: 2.1
orbs:
  react-native: echobind/react-native@0.1.0
workflows:
  version: 2
  main:
    jobs:
      - react-native/node:
          name: node
          filters:
            branches:
              ignore:
                - master
                - beta
                - production
      - react-native/android:
          name: android
          requires:
            - node
          filters:
            branches:
              ignore:
                - master
                - beta
                - production
          build:
            - run:
                name: fastlane adhoc android
                working_directory: android
                command: >
                  bundle exec fastlane adhoc distribute:false
                  build_number:${CIRCLE_BUILD_NUM}
      - react-native/ios:
          name: ios
          requires:
            - node
          filters:
            branches:
              ignore:
                - master
                - beta
                - production
          build:
            - run:
                name: fastlane adhoc ios
                working_directory: ios
                command: >
                  bundle exec fastlane adhoc distribute:false
                  build_number:${CIRCLE_BUILD_NUM}
  alpha:
    jobs:
      - react-native/node:
          name: node (alpha)
          filters:
            branches:
              only: master
      - react-native/android:
          name: android (alpha)
          requires:
            - node (alpha)
          filters:
            branches:
              only: master
          build:
            - run:
                name: fastlane beta android
                working_directory: android
                command: |
                  # APPCENTER_DISTRIBUTE_GROUP=Internal \
                  APPCENTER_OWNER_NAME=HomeHero \
                  APPCENTER_APP_NAME=HomeHero-Android \
                  bundle exec fastlane adhoc build_number:${CIRCLE_BUILD_NUM}
      - react-native/ios:
          name: ios (alpha)
          requires:
            - node (alpha)
          filters:
            branches:
              only: master
          build:
            - run:
                name: fastlane adhoc ios
                working_directory: ios
                command: |
                  # Example passing ENV vars to
                  APPCENTER_DISTRIBUTE_GROUP=Internal \
                  APPCENTER_OWNER_NAME=MyCompany \
                  APPCENTER_APP_NAME=MyApp \
                  bundle exec fastlane adhoc build_number:${CIRCLE_BUILD_NUM}
  beta:
    jobs:
      - react-native/node:
          name: node (beta)
          filters:
            branches:
              only: beta
      - react-native/android:
          name: android (beta)
          requires:
            - node (beta)
          filters:
            branches:
              only: beta
          build:
            - run:
                name: fastlane beta android
                working_directory: android
                command: |
                  bundle exec fastlane beta build_number:${CIRCLE_BUILD_NUM}
  production:
    jobs:
      - react-native/node:
          name: node (production)
          filters:
            branches:
              only: production
      - react-native/android:
          name: android (production)
          requires:
            - node (production)
          filters:
            branches:
              only: production
          build:
            - run:
                name: fastlane production android
                working_directory: android
                command: >
                  bundle exec fastlane production
                  build_number:${CIRCLE_BUILD_NUM}
