version: 2.1

jobs:
  build:
    macos:
      xcode: "12.4.0"
    environment:
      RUBY_VERSION: "2.7.5"
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: source $BASH_ENV
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            - yarn-packages-
      - run: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package.json" }}
            - node-modules-
      - run: yarn install --check-files
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "package.json" }}
      - run: yarn test
