version: 2.1

jobs:
  build:
    macos:
      xcode: 14.1.0
    environment:
      PATH: "/usr/local/opt/node@16/bin:/usr/local/opt/ruby@2.7/bin:$PATH"
    steps:
      - checkout
      - run: brew update
      - run: brew install node@16
      - run: npm install -g yarn
      - run: yarn install
      - run: gem install bundler
      - run: bundle install
      - run: cd ios && pod install
      - run:
        name: Install Git
        command: sudo apt-get update && sudo apt-get install -y git
      - run:
        name: Display Git Path
        command: which git
      - run: |
          xcodebuild \
            -workspace YourApp.xcworkspace \
            -scheme YourApp \
            -destination 'platform=iOS Simulator,name=iPhone 13 Pro Max,OS=15.0' \
            -derivedDataPath build \
            -quiet \
            clean build-for-testing
