version: 2.1

orbs:
  node: circleci/node@4.5.0
  react-native: anvilco/react-native@1.0.1

jobs:
  build:
    macos:
      xcode: "14.1"
    executor:
      name: react-native/default
    steps:
      - checkout
      - node/install
      - react-native/install
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build app
          command: |
            cd ios && pod install && cd ..
            yarn run ios:build
      - store_artifacts:
          path: ios/build/*.ipa

workflows:
  build_and_deploy:
    jobs:
      - build:
          context: deploy