export const ENUM_APP_CHART = {
  PULSE_AM: 'PULSE_AM',
  PULSE_PM: 'PULSE_PM',
  SP02_AM: 'SP02_AM',
  SP02_PM: 'SP02_PM',
};

export enum TYPE_BTN_SOCIAL {
  GOOGLE = 'GOOGLE',
  FACEBOOK = 'FACEBOOK',
  APPLE = 'APPLE',
}
